# Generated by Django 6.0.5 on 2026-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='prices',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='staff_numbers',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(blank=True, to='tour_crud.service'),
        ),
    ]
