# Generated by Django 6.0.5 on 2026-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('phone_number', models.CharField(default='+996', max_length=15)),
                ('gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('education', models.CharField(max_length=200)),
                ('skills', models.TextField()),
            ],
        ),
    ]
