# Generated by Django 6.0.5 on 2026-05-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Напишите название книги')),
                ('author', models.CharField(max_length=100, verbose_name='Напишите название автора')),
                ('description', models.TextField(blank=True, verbose_name='напишите описание')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='загрузите фото')),
                ('genre', models.CharField(blank=True, choices=[('Альтернативная история', 'Альтернативная история'), ('Антиутопия', 'Антиутопия'), ('Биография', 'Биография'), ('Боевик', 'Боевик'), ('Детский', 'Детский'), ('Драма', 'Драма'), ('Комедия', 'Комедия'), ('Криминал', 'Криминал'), ('Научная фантастика', 'Научная фантастика'), ('Научный', 'Научный'), ('Ужас', 'Ужас'), ('Фэнтези', 'Фэнтези')], default='Детский', max_length=100, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, default=20, null=True, verbose_name='Укажите кол-во страниц')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True)),
                ('published_date', models.PositiveIntegerField(blank=True, default=2000, null=True, verbose_name='Укажите год книги')),
                ('language', models.CharField(blank=True, default='Русский', max_length=30, null=True)),
                ('isbn', models.CharField(blank=True, default='0', max_length=20, null=True)),
            ],
        ),
    ]
