# Generated by Django 6.0.5 on 2026-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Напишите имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, verbose_name='Напишите описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('Альтернативная история', 'Альтернативная история'), ('Антиутопия', 'Антиутопия'), ('Биография', 'Биография'), ('Боевик', 'Боевик'), ('Детский', 'Детский'), ('Драма', 'Драма'), ('Комедия', 'Комедия'), ('Криминал', 'Криминал'), ('Научная фантастика', 'Научная фантастика'), ('Научный', 'Научный'), ('Ужас', 'Ужас'), ('Фэнтези', 'Фэнтези')], default='Детский', max_length=100, null=True, verbose_name='Укажите жанр'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='book/', verbose_name='Загрузите фото'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='Укажите ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='Русский', max_length=30, null=True, verbose_name='Укажите язык книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=10, null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(blank=True, default=2000, null=True, verbose_name='Укажите год издания книги'),
        ),
    ]
